/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedCashierRouteImport } from './routes/_authenticated/cashier'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager.index'
import { Route as AuthenticatedManagerSuppliersRouteImport } from './routes/_authenticated/manager.suppliers'
import { Route as AuthenticatedManagerStockRouteImport } from './routes/_authenticated/manager.stock'
import { Route as AuthenticatedManagerSalesRouteImport } from './routes/_authenticated/manager.sales'
import { Route as AuthenticatedManagerProductsRouteImport } from './routes/_authenticated/manager.products'
import { Route as AuthenticatedManagerManualsRouteImport } from './routes/_authenticated/manager.manuals'
import { Route as AuthenticatedManagerForecastRouteImport } from './routes/_authenticated/manager.forecast'
import { Route as AuthenticatedManagerExpensesRouteImport } from './routes/_authenticated/manager.expenses'
import { Route as AuthenticatedManagerCashiersRouteImport } from './routes/_authenticated/manager.cashiers'
import { Route as AuthenticatedManagerCashRouteImport } from './routes/_authenticated/manager.cash'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCashierRoute = AuthenticatedCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerSuppliersRoute =
  AuthenticatedManagerSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerStockRoute =
  AuthenticatedManagerStockRouteImport.update({
    id: '/stock',
    path: '/stock',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerSalesRoute =
  AuthenticatedManagerSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerProductsRoute =
  AuthenticatedManagerProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerManualsRoute =
  AuthenticatedManagerManualsRouteImport.update({
    id: '/manuals',
    path: '/manuals',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerForecastRoute =
  AuthenticatedManagerForecastRouteImport.update({
    id: '/forecast',
    path: '/forecast',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerExpensesRoute =
  AuthenticatedManagerExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerCashiersRoute =
  AuthenticatedManagerCashiersRouteImport.update({
    id: '/cashiers',
    path: '/cashiers',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerCashRoute =
  AuthenticatedManagerCashRouteImport.update({
    id: '/cash',
    path: '/cash',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cashier': typeof AuthenticatedCashierRoute
  '/manager': typeof AuthenticatedManagerRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRoute
  '/manager/cash': typeof AuthenticatedManagerCashRoute
  '/manager/cashiers': typeof AuthenticatedManagerCashiersRoute
  '/manager/expenses': typeof AuthenticatedManagerExpensesRoute
  '/manager/forecast': typeof AuthenticatedManagerForecastRoute
  '/manager/manuals': typeof AuthenticatedManagerManualsRoute
  '/manager/products': typeof AuthenticatedManagerProductsRoute
  '/manager/sales': typeof AuthenticatedManagerSalesRoute
  '/manager/stock': typeof AuthenticatedManagerStockRoute
  '/manager/suppliers': typeof AuthenticatedManagerSuppliersRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cashier': typeof AuthenticatedCashierRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/manager/cash': typeof AuthenticatedManagerCashRoute
  '/manager/cashiers': typeof AuthenticatedManagerCashiersRoute
  '/manager/expenses': typeof AuthenticatedManagerExpensesRoute
  '/manager/forecast': typeof AuthenticatedManagerForecastRoute
  '/manager/manuals': typeof AuthenticatedManagerManualsRoute
  '/manager/products': typeof AuthenticatedManagerProductsRoute
  '/manager/sales': typeof AuthenticatedManagerSalesRoute
  '/manager/stock': typeof AuthenticatedManagerStockRoute
  '/manager/suppliers': typeof AuthenticatedManagerSuppliersRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cashier': typeof AuthenticatedCashierRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRouteWithChildren
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/manager/cash': typeof AuthenticatedManagerCashRoute
  '/_authenticated/manager/cashiers': typeof AuthenticatedManagerCashiersRoute
  '/_authenticated/manager/expenses': typeof AuthenticatedManagerExpensesRoute
  '/_authenticated/manager/forecast': typeof AuthenticatedManagerForecastRoute
  '/_authenticated/manager/manuals': typeof AuthenticatedManagerManualsRoute
  '/_authenticated/manager/products': typeof AuthenticatedManagerProductsRoute
  '/_authenticated/manager/sales': typeof AuthenticatedManagerSalesRoute
  '/_authenticated/manager/stock': typeof AuthenticatedManagerStockRoute
  '/_authenticated/manager/suppliers': typeof AuthenticatedManagerSuppliersRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cashier'
    | '/manager'
    | '/orders'
    | '/manager/cash'
    | '/manager/cashiers'
    | '/manager/expenses'
    | '/manager/forecast'
    | '/manager/manuals'
    | '/manager/products'
    | '/manager/sales'
    | '/manager/stock'
    | '/manager/suppliers'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cashier'
    | '/orders'
    | '/manager/cash'
    | '/manager/cashiers'
    | '/manager/expenses'
    | '/manager/forecast'
    | '/manager/manuals'
    | '/manager/products'
    | '/manager/sales'
    | '/manager/stock'
    | '/manager/suppliers'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cashier'
    | '/_authenticated/manager'
    | '/_authenticated/orders'
    | '/_authenticated/manager/cash'
    | '/_authenticated/manager/cashiers'
    | '/_authenticated/manager/expenses'
    | '/_authenticated/manager/forecast'
    | '/_authenticated/manager/manuals'
    | '/_authenticated/manager/products'
    | '/_authenticated/manager/sales'
    | '/_authenticated/manager/stock'
    | '/_authenticated/manager/suppliers'
    | '/_authenticated/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cashier': {
      id: '/_authenticated/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof AuthenticatedCashierRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/suppliers': {
      id: '/_authenticated/manager/suppliers'
      path: '/suppliers'
      fullPath: '/manager/suppliers'
      preLoaderRoute: typeof AuthenticatedManagerSuppliersRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/stock': {
      id: '/_authenticated/manager/stock'
      path: '/stock'
      fullPath: '/manager/stock'
      preLoaderRoute: typeof AuthenticatedManagerStockRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/sales': {
      id: '/_authenticated/manager/sales'
      path: '/sales'
      fullPath: '/manager/sales'
      preLoaderRoute: typeof AuthenticatedManagerSalesRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/products': {
      id: '/_authenticated/manager/products'
      path: '/products'
      fullPath: '/manager/products'
      preLoaderRoute: typeof AuthenticatedManagerProductsRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/manuals': {
      id: '/_authenticated/manager/manuals'
      path: '/manuals'
      fullPath: '/manager/manuals'
      preLoaderRoute: typeof AuthenticatedManagerManualsRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/forecast': {
      id: '/_authenticated/manager/forecast'
      path: '/forecast'
      fullPath: '/manager/forecast'
      preLoaderRoute: typeof AuthenticatedManagerForecastRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/expenses': {
      id: '/_authenticated/manager/expenses'
      path: '/expenses'
      fullPath: '/manager/expenses'
      preLoaderRoute: typeof AuthenticatedManagerExpensesRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/cashiers': {
      id: '/_authenticated/manager/cashiers'
      path: '/cashiers'
      fullPath: '/manager/cashiers'
      preLoaderRoute: typeof AuthenticatedManagerCashiersRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/cash': {
      id: '/_authenticated/manager/cash'
      path: '/cash'
      fullPath: '/manager/cash'
      preLoaderRoute: typeof AuthenticatedManagerCashRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
  }
}

interface AuthenticatedManagerRouteChildren {
  AuthenticatedManagerCashRoute: typeof AuthenticatedManagerCashRoute
  AuthenticatedManagerCashiersRoute: typeof AuthenticatedManagerCashiersRoute
  AuthenticatedManagerExpensesRoute: typeof AuthenticatedManagerExpensesRoute
  AuthenticatedManagerForecastRoute: typeof AuthenticatedManagerForecastRoute
  AuthenticatedManagerManualsRoute: typeof AuthenticatedManagerManualsRoute
  AuthenticatedManagerProductsRoute: typeof AuthenticatedManagerProductsRoute
  AuthenticatedManagerSalesRoute: typeof AuthenticatedManagerSalesRoute
  AuthenticatedManagerStockRoute: typeof AuthenticatedManagerStockRoute
  AuthenticatedManagerSuppliersRoute: typeof AuthenticatedManagerSuppliersRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
}

const AuthenticatedManagerRouteChildren: AuthenticatedManagerRouteChildren = {
  AuthenticatedManagerCashRoute: AuthenticatedManagerCashRoute,
  AuthenticatedManagerCashiersRoute: AuthenticatedManagerCashiersRoute,
  AuthenticatedManagerExpensesRoute: AuthenticatedManagerExpensesRoute,
  AuthenticatedManagerForecastRoute: AuthenticatedManagerForecastRoute,
  AuthenticatedManagerManualsRoute: AuthenticatedManagerManualsRoute,
  AuthenticatedManagerProductsRoute: AuthenticatedManagerProductsRoute,
  AuthenticatedManagerSalesRoute: AuthenticatedManagerSalesRoute,
  AuthenticatedManagerStockRoute: AuthenticatedManagerStockRoute,
  AuthenticatedManagerSuppliersRoute: AuthenticatedManagerSuppliersRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
}

const AuthenticatedManagerRouteWithChildren =
  AuthenticatedManagerRoute._addFileChildren(AuthenticatedManagerRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCashierRoute: typeof AuthenticatedCashierRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRouteWithChildren
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCashierRoute: AuthenticatedCashierRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRouteWithChildren,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
